# Generated by Django 5.2.3 on 2026-02-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deliver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
