# Generated by Django 5.2.3 on 2026-02-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deliver', '0002_remove_product_stock_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['group_name', 'name'], 'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.AddField(
            model_name='subcategory',
            name='group_name',
            field=models.CharField(help_text='Header for the mega-menu column', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
