# Generated by Django 5.2.3 on 2026-02-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deliver', '0003_alter_subcategory_options_subcategory_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.CharField(blank=True, choices=[('new', 'New Product'), ('popular', 'Popular Wine')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
