# Generated by Django 5.2.3 on 2026-02-20 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deliver', '0004_product_feature_product_old_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['group__name', 'name'], 'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='group_name',
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, help_text='Country of origin of the product', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='Deliver.category')),
            ],
        ),
        migrations.AddField(
            model_name='subcategory',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='Deliver.group'),
        ),
    ]
