# Generated by Django 5.2.3 on 2026-02-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deliver', '0005_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='group',
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['group_name', 'name'], 'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.AddField(
            model_name='subcategory',
            name='group_name',
            field=models.CharField(help_text='Header for the mega-menu column', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
