# Generated by Django 5.2.3 on 2026-02-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deliver', '0007_order_checkout_request_id_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='building_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='door_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('failed', 'Payment Failed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20),
        ),
    ]
