# Generated by Django 5.2.3 on 2026-03-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deliver', '0012_alter_cart_user_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accolades',
            field=models.TextField(blank=True, help_text='Awards and recognition', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='alcohol_content',
            field=models.CharField(blank=True, help_text='e.g. 8%', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='appearance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='aroma',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='finish',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GTIN-8'),
        ),
        migrations.AddField(
            model_name='product',
            name='palate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='75cl', max_length=50),
        ),
    ]
