# Generated by Django 5.2.3 on 2026-03-03 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deliver', '0013_product_accolades_product_alcohol_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='alcohol_content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='appearance',
        ),
        migrations.RemoveField(
            model_name='product',
            name='aroma',
        ),
        migrations.RemoveField(
            model_name='product',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gtin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='palate',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together={('product', 'user')},
        ),
    ]
