# Generated by Django 5.2.3 on 2026-03-10 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deliver', '0014_remove_product_alcohol_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('driver_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Driver Assigned'), ('picked', 'Order Picked'), ('on_the_way', 'On The Way'), ('arriving', 'Arriving Soon'), ('delivered', 'Delivered')], default='assigned', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='Deliver.order')),
            ],
        ),
    ]
