# Generated by Django 5.2.3 on 2026-03-18 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deliver', '0016_alter_websiterating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiterating',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Deliver.order'),
        ),
    ]
